### ISSUE TITLE
Migration issue upgrading from 1.0.2 to 1.0.5

### ISSUE THREAD

**Issue by bfrederix** [PhilipGarnero/django-rest-framework-social-oauth2#81]
Hello,

When I pip install 1.0.5 from 1.0.2, I get a migration issue when I try to do a runserver or a migrate.

`(django-voteprov) ~/projects/django-voteprov (git::master) $ python manage.py migrate
/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/db/migrations/loader.py", line 281, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/Users/freddy/.pyenv/versions/django-voteprov/lib/python2.7/site-packages/django/db/migrations/loader.py", line 264, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration social_django.0004_auto_20160423_0400 dependencies reference nonexistent parent node (u'social_django', u'0003_alter_email_max_length')`

Any idea what might be the solution? I'm also struggling to find the migration files.

**Comment by PhilipGarnero** [comment]
You should check [migrations instructions](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md) from python-social-auth.
